### ISSUE TITLE
The webpage acts weird at 2022/11

### ISSUE THREAD

**Issue by RPKQ** [benkajaja/NTU-Court-Search#32]
As title. I need this cool thing to see which field we have (although I currently dont play with CS)

**Comment by benkajaja** [comment]
Hi,

Nice to meet you, developer.

It looks like that physical education office upgraded their renting system.
As a result, the existing API is deprecated.

I will adapt our crawler to fit the latest renting system ASAP. Thanks for your kind reminder.
